name: Build ROM file
on: [push]
jobs:
  Default:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: Download and install sjasmplus and Python libs
        run: make prepare_worker
      - name: Build project 
        run: make
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: quorum-1024plus-rom
          path: quorum-1024plus.rom
      
